### PR TITLE
fix: change Accordion state wrt its props

### PR DESCRIPTION
**Pull request by ranjith-sg**
Hi Kalin, I have made changes on Accordion component. Please review it and merge it with master If the changes are fine.

### CODE REVIEW

**Comment by marielakas** [comment]
The props must NOT be used to set the components's state. This is an anti-pattern. Instead of explicitly setting the collapsed state to match the collapsed prop and then manually updating the state just use the collapsed prop, meaning: 

<Box title={this.props.title} showAccordeon {...this.props} collapsed={this.state.collapsed} onToggle={this.handleToggle}>
 
should be  rewritten to

<Box title={this.props.title} showAccordeon {...this.props}  onToggle={this.handleToggle}>

Actually the best approach here would be to rewrite the component as a functional stateless component, because the local state is useless.

**Comment by ranjith-sg** [comment]
Please check the latest changes, I have removed the props dependence with its state. Please merge it If the changes are fine.

**Comment by venconi91** [comment]
Keep in mind that this is a breaking change after this patch, because some modules depend on this component and they rely on the fact that Accordion component will contain the state and now these modules should change (they should manage the state of the Accordion)

**Comment by ranjith-sg** [comment]
@marielakas, your suggested approach
`<Box title={this.props.title} showAccordeon {...this.props} onToggle={this.handleToggle}>`
will affect other ut-modules which are consuming the Accordion element if its stateless. If the Accordion is stateless we should go to revisit, all the places where the element has used.

I think having a **local state is fine, when a element have event itself**(same as for Accordion 
 element). Please consider the below scenario(If it have local state), The Accordion element initial state is depend on it props, So we should change the state, when the props has changed.

Please correct me If anything wrong and share your thoughts also.

**Pull request closed without merging**
