### PR TITLE
Patch/acapulco

### PR DESCRIPTION
**Pull request by lawanyaselvamani**

### CODE REVIEW

**Comment by simeonpp** [comment]
@ChrispCode & @marielakas please review. 
@lawanyaselvamani there is jenkins errors, please fix them.

**Comment by ChrispCode** [comment]
The build had failed! I reruned it. Let's see!

**Comment by ChrispCode** [comment]
OK, there is a problem with the branch, I get it now!

**Comment by velchovski-sg** [comment]
There is a problem with this pull request.
You cannot merge patch/* into minor/rc-acapulco because ut-tools won't allow that.
That's why the **ut-front-react_post-commit** build has failed.
"Error: Release version mismatch: Version rc-acapulco can't be released from version acapulco"
Please make another branch that is not named patch/*, move the changes there and submit another pull request.

**Pull request closed without merging**
