### PR TITLE
fix: login screen - password only to be mandatory, deprecated ref err…

### PR DESCRIPTION
**Pull request by mshumankov**
…or DIG-28

review please
@beyrul

### CODE REVIEW

**Review by beyrul — APPROVED** [review]

**Comment by kalinkrustev** [comment]
Getting rid of the deprecated ref is a noble cause, but I can't be sure it is not breaking something.
So I will try to collect some opinions from others.
The proper time for such change could be before some comprehensive UAT.

@stoberov @goodlifeinc , what do you think?

**Comment by goodlifeinc** [comment]
Hi,
sorry to see this request a bit late.

Noble cause indeed it is :)

I will try this branch in the dfa implementations and let you know if its fine.

**Comment by goodlifeinc** [comment]
I've played around with the grids and filters and all seem to be working correctly.
I couldn't take a picture of myself in the DocumentUpload/Camera.js component.
I couldn't find and test the Cropper.js functionalities.
I couldn't test the Login page as the dfa projects use ut-portal.

**Review by goodlifeinc — APPROVED** [review]

**Comment by stoberov** [comment]
Sorry, I am unable to test myself. If Evgeni has played with this, then ... thumbs up from me :))

**Review by stoberov — CHANGES_REQUESTED** [review]
Only there is a merge conflict now ... +1 after it's resolved.

**Pull request merged**
